# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

namespace: logging

images:
  - name: docker.elastic.co/kibana/kibana
    newName: reg.sighup.io/sighupio/fury/kibana
    newTag: 7.10.1

resources:
  - kibana.yml
