# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - logging.banzaicloud.io_clusterflows.yaml
  - logging.banzaicloud.io_clusteroutputs.yaml
  - logging.banzaicloud.io_flows.yaml
  - logging.banzaicloud.io_loggings.yaml
  - logging.banzaicloud.io_outputs.yaml
  - logging-extensions.banzaicloud.io_eventtailers.yaml
  - logging-extensions.banzaicloud.io_hosttailers.yaml