# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - init-job.yaml
  - service.yaml
  - sts.yaml

vars:
  - name: MINIO_NAMESPACE
    objref:
      kind: Service
      name: minio
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: MINIO_SERVICE_NAME
    objref:
      kind: Service
      name: minio
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: MINIO_STS_NAME
    objref:
      kind: StatefulSet
      name: minio
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.name
#  - name: MINIO_SETUP_JOB_NAME
#    objref:
#      kind: Job
#      name: minio-setup
#      apiVersion: batch/v1
#    fieldref:
#      fieldpath: metadata.name

images:
  - name: minio/minio
    newName: registry.sighup.io/fury/minio
    newTag: RELEASE.2021-05-26T00-22-46Z
  - name: minio/mc
    newName: registry.sighup.io/fury/minio/mc
    newTag: RELEASE.2021-05-18T03-39-44Z
  - name: groundnuty/k8s-wait-for
    newName: registry.sighup.io/fury/groundnuty/k8s-wait-for
    newTag: v1.4

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: minio-credentials
  envs: 
    - cloud-credentials.env
